import { Router } from 'express';
import { createLinkController, createMilestoneController, createPhaseController, deleteLinkController, deleteMilestoneController, deletePhaseController, getMilestoneController, listLinksController, listMilestonesController, listPhasesController, updateLinkController, updateMilestoneController, updatePhaseController } from '../controllers/project-planning.controller';
import { createBudgetLineController, createSpendRecordController, financialSummaryController, listBudgetLinesController, listSpendRecordsController } from '../controllers/finance.controller';
import { createIssueController, createRiskController, listIssuesController, listRisksController } from '../controllers/risk-issue.controller';
import { projectAllocationsController } from '../controllers/resource.controller';
import { requireAuth } from '../middleware/require-auth.middleware';

export const projectPlanningRouter = Router({ mergeParams: true });
export const milestoneRouter = Router();

projectPlanningRouter.get('/links', requireAuth, listLinksController);
projectPlanningRouter.post('/links', requireAuth, createLinkController);
projectPlanningRouter.patch('/links/:linkId', requireAuth, updateLinkController);
projectPlanningRouter.delete('/links/:linkId', requireAuth, deleteLinkController);
projectPlanningRouter.get('/phases', requireAuth, listPhasesController);
projectPlanningRouter.post('/phases', requireAuth, createPhaseController);
projectPlanningRouter.patch('/phases/:phaseId', requireAuth, updatePhaseController);
projectPlanningRouter.delete('/phases/:phaseId', requireAuth, deletePhaseController);
projectPlanningRouter.get('/milestones', requireAuth, listMilestonesController);
projectPlanningRouter.post('/milestones', requireAuth, createMilestoneController);
projectPlanningRouter.get('/budget-lines', requireAuth, listBudgetLinesController);
projectPlanningRouter.post('/budget-lines', requireAuth, createBudgetLineController);
projectPlanningRouter.get('/spend-records', requireAuth, listSpendRecordsController);
projectPlanningRouter.post('/spend-records', requireAuth, createSpendRecordController);
projectPlanningRouter.get('/financial-summary', requireAuth, financialSummaryController);
projectPlanningRouter.get('/risks', requireAuth, listRisksController);
projectPlanningRouter.post('/risks', requireAuth, createRiskController);
projectPlanningRouter.get('/issues', requireAuth, listIssuesController);
projectPlanningRouter.post('/issues', requireAuth, createIssueController);
projectPlanningRouter.get('/allocations', requireAuth, projectAllocationsController);
milestoneRouter.get('/:id', requireAuth, getMilestoneController);
milestoneRouter.patch('/:id', requireAuth, updateMilestoneController);
milestoneRouter.delete('/:id', requireAuth, deleteMilestoneController);
