import type { NextFunction, Request, Response } from 'express';
import { createProjectLink, createProjectMilestone, createProjectPhase, deleteMilestone, deleteProjectLink, deleteProjectPhase, getMilestone, listProjectLinks, listProjectMilestones, listProjectPhases, updateMilestone, updateProjectLink, updateProjectPhase } from '../services/project-planning.service';
import { parseUuid, requireUser } from '../utils/request.util';

function projectId(request: Request): string { return parseUuid(request.params.projectId); }

export async function listLinksController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await listProjectLinks(requireUser(request.user), projectId(request))); } catch (error) { next(error); } }
export async function createLinkController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.status(201).json(await createProjectLink(requireUser(request.user), projectId(request), request.body)); } catch (error) { next(error); } }
export async function updateLinkController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await updateProjectLink(requireUser(request.user), projectId(request), parseUuid(request.params.linkId), request.body)); } catch (error) { next(error); } }
export async function deleteLinkController(request: Request, response: Response, next: NextFunction): Promise<void> { try { await deleteProjectLink(requireUser(request.user), projectId(request), parseUuid(request.params.linkId)); response.status(204).send(); } catch (error) { next(error); } }
export async function listPhasesController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await listProjectPhases(requireUser(request.user), projectId(request))); } catch (error) { next(error); } }
export async function createPhaseController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.status(201).json(await createProjectPhase(requireUser(request.user), projectId(request), request.body)); } catch (error) { next(error); } }
export async function updatePhaseController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await updateProjectPhase(requireUser(request.user), projectId(request), parseUuid(request.params.phaseId), request.body)); } catch (error) { next(error); } }
export async function deletePhaseController(request: Request, response: Response, next: NextFunction): Promise<void> { try { await deleteProjectPhase(requireUser(request.user), projectId(request), parseUuid(request.params.phaseId)); response.status(204).send(); } catch (error) { next(error); } }
export async function listMilestonesController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await listProjectMilestones(requireUser(request.user), projectId(request))); } catch (error) { next(error); } }
export async function getMilestoneController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await getMilestone(requireUser(request.user), parseUuid(request.params.id))); } catch (error) { next(error); } }
export async function createMilestoneController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.status(201).json(await createProjectMilestone(requireUser(request.user), projectId(request), request.body)); } catch (error) { next(error); } }
export async function updateMilestoneController(request: Request, response: Response, next: NextFunction): Promise<void> { try { response.json(await updateMilestone(requireUser(request.user), parseUuid(request.params.id), request.body)); } catch (error) { next(error); } }
export async function deleteMilestoneController(request: Request, response: Response, next: NextFunction): Promise<void> { try { await deleteMilestone(requireUser(request.user), parseUuid(request.params.id)); response.status(204).send(); } catch (error) { next(error); } }
